-- MySQL Script generated by MySQL Workbench
-- Mon Jan  4 13:35:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema caronapp_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema caronapp_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caronapp_bd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `caronapp_bd` ;

-- -----------------------------------------------------
-- Table `caronapp_bd`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `facebook_id` VARCHAR(45) NULL DEFAULT NULL,
  `ride_as_driver` INT NULL DEFAULT NULL,
  `ride_as_user` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `car_brand` VARCHAR(50) NULL DEFAULT NULL,
  `car_model` VARCHAR(45) NULL DEFAULT NULL,
  `car_color` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `picture` VARCHAR(200) NULL DEFAULT NULL,
  `password` LONGTEXT NOT NULL,
  `activated` TINYINT NULL DEFAULT NULL,
  `course` VARCHAR(10) NULL DEFAULT NULL,
  `course_ingression` VARCHAR(6) NULL DEFAULT NULL,
  `show_number` TINYINT NULL DEFAULT NULL,
  `id_region` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`activations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`activations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` INT NOT NULL,
  `users_id` INT NOT NULL,
  `expire_at` DATETIME NOT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_user_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_activations_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `caronapp_bd`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`badges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`badges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`blocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`blocks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reason` VARCHAR(95) NULL DEFAULT NULL,
  `ban_date` DATETIME NULL DEFAULT NULL,
  `email` VARCHAR(65) NULL DEFAULT NULL,
  `id_user` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`change_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`change_password` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(56) NOT NULL,
  `id_user` INT UNSIGNED NOT NULL,
  `expires_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`provinces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `acronym` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`regions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(155) NULL DEFAULT NULL,
  `keywords` VARCHAR(100) NULL DEFAULT NULL,
  `times` JSON NULL DEFAULT NULL,
  `id_province` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `region-province` (`id_province` ASC) VISIBLE,
  CONSTRAINT `fk_regionsXXX_provinces1`
    FOREIGN KEY (`id_province`)
    REFERENCES `caronapp_bd`.`provinces` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`rides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`rides` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `outgoing` TINYINT NULL DEFAULT NULL,
  `spots` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `type` VARCHAR(12) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `route` JSON NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `id_region` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_region_idx` (`id_region` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_rides_regions1`
    FOREIGN KEY (`id_region`)
    REFERENCES `caronapp_bd`.`regions` (`id`),
  CONSTRAINT `fk_rides_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `caronapp_bd`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`confirmed_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`confirmed_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `id_route_point` INT NOT NULL,
  `message` VARCHAR(45) NULL DEFAULT NULL,
  `id_ride` INT NOT NULL,
  `id_user` INT NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_ride_idx` (`id_ride` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_pendent_users_rides10`
    FOREIGN KEY (`id_ride`)
    REFERENCES `caronapp_bd`.`rides` (`id`),
  CONSTRAINT `fk_pendent_users_users10`
    FOREIGN KEY (`id_user`)
    REFERENCES `caronapp_bd`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`destinations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`destinations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lat` DOUBLE NULL DEFAULT NULL,
  `long` DOUBLE NULL DEFAULT NULL,
  `picture` LONGTEXT NULL DEFAULT NULL,
  `reference` VARCHAR(45) NULL DEFAULT NULL,
  `region` VARCHAR(45) NULL DEFAULT NULL,
  `isActive` TINYINT NULL DEFAULT NULL,
  `picture_small` LONGTEXT NULL DEFAULT NULL,
  `pointscol` VARCHAR(45) NULL DEFAULT NULL,
  `id_region` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_region-destination_idx` (`id_region` ASC) VISIBLE,
  CONSTRAINT `fk_points_regions10`
    FOREIGN KEY (`id_region`)
    REFERENCES `caronapp_bd`.`regions` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`feedbacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`feedbacks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL DEFAULT NULL,
  `feedback` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `log` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(96) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `id_ride` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_ride_idx` (`id_ride` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_messages_rides1`
    FOREIGN KEY (`id_ride`)
    REFERENCES `caronapp_bd`.`rides` (`id`),
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `caronapp_bd`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`pendent_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`pendent_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `id_route_point` INT NOT NULL,
  `message` VARCHAR(45) NULL DEFAULT NULL,
  `id_ride` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_pendent_users_rides1_idx` (`id_ride` ASC) VISIBLE,
  INDEX `fk_pendent_users_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_pendent_users_rides1`
    FOREIGN KEY (`id_ride`)
    REFERENCES `caronapp_bd`.`rides` (`id`),
  CONSTRAINT `fk_pendent_users_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `caronapp_bd`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`placeholder_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`placeholder_copy1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`points` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lat` DOUBLE NULL DEFAULT NULL,
  `long` DOUBLE NULL DEFAULT NULL,
  `picture` LONGTEXT NULL DEFAULT NULL,
  `reference` VARCHAR(45) NULL DEFAULT NULL,
  `region` VARCHAR(45) NULL DEFAULT NULL,
  `isActive` TINYINT NULL DEFAULT NULL,
  `picture_small` LONGTEXT NULL DEFAULT NULL,
  `pointscol` VARCHAR(45) NULL DEFAULT NULL,
  `id_region` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_points_regions1_idx` (`id_region` ASC) VISIBLE,
  CONSTRAINT `fk_points_regions1`
    FOREIGN KEY (`id_region`)
    REFERENCES `caronapp_bd`.`regions` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`preferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`preferences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `points_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_user_idx` (`users_id` ASC) VISIBLE,
  INDEX `id_point-preferences_idx` (`points_id` ASC) VISIBLE,
  CONSTRAINT `fk_preferences_points1`
    FOREIGN KEY (`points_id`)
    REFERENCES `caronapp_bd`.`points` (`id`),
  CONSTRAINT `fk_preferences_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `caronapp_bd`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`rating_badges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`rating_badges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_rating` INT NOT NULL,
  `id_badge` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_badge_idx` (`id_badge` ASC) VISIBLE,
  INDEX `id_rating_idx` (`id_rating` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `review` VARCHAR(120) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `id_confirmed_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_confirmed_user_idx` (`id_confirmed_user` ASC) VISIBLE,
  CONSTRAINT `fk_ratings_confirmed_users1`
    FOREIGN KEY (`id_confirmed_user`)
    REFERENCES `caronapp_bd`.`confirmed_users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`routes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(35) NOT NULL,
  `id_user` INT NOT NULL,
  `id_destination` INT NOT NULL,
  `id_region` INT NOT NULL,
  `origin` JSON NOT NULL,
  `points` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_destination_idx` (`id_destination` ASC) VISIBLE,
  INDEX `id_region_idx` (`id_region` ASC) VISIBLE,
  CONSTRAINT `fk_routes_destinations1`
    FOREIGN KEY (`id_destination`)
    REFERENCES `caronapp_bd`.`destinations` (`id`),
  CONSTRAINT `fk_routes_regions1`
    FOREIGN KEY (`id_region`)
    REFERENCES `caronapp_bd`.`regions` (`id`),
  CONSTRAINT `fk_routes_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `caronapp_bd`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` LONGTEXT NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_sessions_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `caronapp_bd`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`sponsors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`sponsors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `picture` VARCHAR(120) NULL DEFAULT NULL,
  `order` INT NULL DEFAULT NULL,
  `link` VARCHAR(80) NULL DEFAULT NULL,
  `name` VARCHAR(45) NOT NULL,
  `text` LONGTEXT NULL DEFAULT NULL,
  `id_region` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_region_idx` (`id_region` ASC) VISIBLE,
  CONSTRAINT `fk_sponsors_regions1`
    FOREIGN KEY (`id_region`)
    REFERENCES `caronapp_bd`.`regions` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`suggestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`suggestions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(105) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(12) NOT NULL,
  `id_region` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_region_idx` (`id_region` ASC) VISIBLE,
  CONSTRAINT `fk_types_regions1`
    FOREIGN KEY (`id_region`)
    REFERENCES `caronapp_bd`.`regions` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`universities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`universities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `regions_id` INT NOT NULL,
  `picture` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_region_idx` (`regions_id` ASC) VISIBLE,
  CONSTRAINT `fk_universities_regions1`
    FOREIGN KEY (`regions_id`)
    REFERENCES `caronapp_bd`.`regions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `IDX_78a916df40e02a9deb1c4b75ed` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `caronapp_bd`.`warnings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caronapp_bd`.`warnings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `button` VARCHAR(45) NULL DEFAULT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_warnings_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `caronapp_bd`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
